package cz.pluscare.resourcegenerator.parser.lproj

import cz.pluscare.resourcegenerator.reader.Language
import cz.pluscare.resourcegenerator.reader.ResourceElement
import cz.pluscare.resourcegenerator.extensions.emojiText
import cz.pluscare.resourcegenerator.parser.ResourceParser
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.stereotype.Component

@Component
@Qualifier("LprojParser")
class LprojParser @Autowired constructor() : ResourceParser {

    override fun getParsedText(language: Language, values: List<ResourceElement>): LprojText? {
        return if (values.isEmpty()) null
        else LprojText.empty().apply {
            generateHeaderComment()
            generateCopyrightComment()
            addLanguageCode(language)
            values.forEach { addResourceElement(it) }
        }
    }

    private fun LprojText.generateHeaderComment() {
        value += "<!-- WARNING: Autogenerated file -->\n"
    }

    private fun LprojText.generateCopyrightComment() {
        val emoji = emojiText(0x1F1E8, 0x1F1FF)
        value += "<!-- Generated by $emoji © Plus Care s.r.o. -->\n"
    }

    private fun LprojText.addLanguageCode(language: Language) {
        value += "\"lang_code\" = \"${language.code}\"\n\n"
    }

    private fun LprojText.addResourceElement(element: ResourceElement) {
        value += "<*  ${element.comment} *>\n"
        value += "\"${element.id}\" = \"${element.value}\"\n\n"
    }

}